apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-demo-fe-config
  namespace: demo
data:
  VITE_API_BASE_URL: "http://argo-rollouts-demo-be.demo.svc.cluster.local:8000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts-demo-fe
  namespace: demo
  labels:
    app: argo-rollouts-demo-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-rollouts-demo-fe
  template:
    metadata:
      labels:
        app: argo-rollouts-demo-fe
    spec:
      containers:
        - name: argo-rollouts-demo-fe
          image: argo-rollouts-demo-fe:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: argo-rollouts-demo-fe-config
                  key: VITE_API_BASE_URL
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-demo-fe-service
  namespace: demo
spec:
  selector:
    app: argo-rollouts-demo-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
