name: Build and Push Backend to ACR

on:
  push:
    branches: [ main ]
    paths:
      - 'argo-rollouts-demo-be/**'
  workflow_dispatch:

env:
  REGISTRY: playgroundacr1234.azurecr.io
  IMAGE_NAME: argo-rollouts-demo-be
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login -n $(echo ${{ env.REGISTRY }} | cut -d'.' -f1)

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./argo-rollouts-demo-be
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest 